// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fansqz/fancode-backend/common/config"
	"github.com/fansqz/fancode-backend/controller"
	"github.com/fansqz/fancode-backend/controller/admin"
	"github.com/fansqz/fancode-backend/controller/user"
	"github.com/fansqz/fancode-backend/dao"
	"github.com/fansqz/fancode-backend/interceptor"
	"github.com/fansqz/fancode-backend/routers"
	"github.com/fansqz/fancode-backend/service/common_service"
	"github.com/fansqz/fancode-backend/service/system_service"
	"github.com/fansqz/fancode-backend/service/user_saved_code_service"
	"github.com/fansqz/fancode-backend/service/visual_debug_servcie"
	"github.com/fansqz/fancode-backend/service/visual_document_service"
	"net/http"
)

// Injectors from wire.go:

func initApp(appConfig *config.AppConfig) (*http.Server, error) {
	sysUserDao := dao.NewSysUserDao()
	sysMenuDao := dao.NewSysMenuDao()
	sysRoleDao := dao.NewSysRoleDao()
	authService := common_service.NewAuthService(appConfig, sysUserDao, sysMenuDao, sysRoleDao)
	authController := controller.NewAuthController(authService)
	accountService := common_service.NewAccountService(appConfig, sysUserDao, sysRoleDao)
	accountController := controller.NewAccountController(accountService)
	commonService := common_service.NewCommonService(appConfig)
	commonController := controller.NewCommonController(commonService)
	userSavedCodeDao := dao.NewUserSavedCodeDao()
	userSavedCodeService := user_saved_code_service.NewUserSavedCodeService(appConfig, userSavedCodeDao)
	userSavedCodeHandler := user.NewUserSavedCodeHandler(userSavedCodeService)
	sysApiDao := dao.NewSysApiDao()
	sysApiService := system_service.NewSysApiService(sysApiDao)
	sysApiController := admin.NewSysApiController(sysApiService)
	sysMenuService := system_service.NewSysMenuService(sysMenuDao)
	sysMenuController := admin.NewSysMenuController(sysMenuService)
	sysRoleService := system_service.NewSysRoleService(sysRoleDao)
	sysRoleController := admin.NewSysRoleController(sysRoleService)
	sysUserService := system_service.NewSysUserService(appConfig, sysUserDao, sysRoleDao)
	sysUserController := admin.NewSysUserController(sysUserService)
	visualDocumentDao := dao.NewVisualDocumentDao()
	visualDocumentService := visual_document_service.NewVisualDocumentService(visualDocumentDao, appConfig)
	visualDocumentManageController := admin.NewVisualDocumentManageController(visualDocumentService)
	visualDocumentBankDao := dao.NewVisualDocumentBankDao()
	visualDocumentBankService := visual_document_service.NewVisualDocumentBankService(appConfig, visualDocumentBankDao, visualDocumentDao, sysUserDao)
	visualDocumentBankManageController := admin.NewVisualDocumentBankManageController(visualDocumentBankService)
	debugService := visual_debug_servcie.NewDebugService(appConfig)
	debugController := user.NewDebugController(debugService)
	visualService := visual_debug_servcie.NewVisualService()
	visualController := user.NewVisualController(visualService)
	visualDocumentController := user.NewVisualDocumentController(visualDocumentService)
	visualDocumentBankController := user.NewVisualDocumentBankController(visualDocumentBankService)
	recoverPanicInterceptor := interceptor.NewRecoverPanicInterceptor()
	corsInterceptor := interceptor.NewCorsInterceptor()
	requestInterceptor := interceptor.NewRequestInterceptor(sysRoleService, sysUserService)
	loggerInterceptor := interceptor.NewLoggerInterceptor()
	engine := routers.SetupRouter(authController, accountController, commonController, userSavedCodeHandler, sysApiController, sysMenuController, sysRoleController, sysUserController, visualDocumentManageController, visualDocumentBankManageController, debugController, visualController, visualDocumentController, visualDocumentBankController, appConfig, recoverPanicInterceptor, corsInterceptor, requestInterceptor, loggerInterceptor)
	server := newApp(engine, appConfig)
	return server, nil
}
